name: '${name}'
version: ${version}
main: ron.thewizard.loretext.LoreText
authors: [ xGinko ]
description: '${description}'
website: '${url}'
api-version: '1.20'
folia-supported: true

commands:
  loretext:
    usage: /loretext textfile
    description: LoreText command